### ISSUE TITLE
XML comments not imported under some conditions

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#20]
I have a .NET class defined like this:

```
    /// <summary>
    /// Returns a subset of the collection based on a condition.
    /// </summary>
    /// <param name="predicate">
    /// The condition to use.
    /// </param>
    /// <returns>
    /// A set of items satisfying the condition.
    /// </returns>
    public IEnumerable<IField> Where(Func<IField, bool> predicate)
```

When I import it, there is nothing in the Main tab (i.e. no summary) and nothing in the Return editbox in the Class Info tab. I suspect this is due to the Func parameter which I mentioned in another issue isn't imported correctly into the Parameters editbox because other methods don't have this issue.

**Comment by DougHennig** [comment]
This also happens with a constructor defined as:

```
    /// <summary>
    /// Constructor.
    /// </summary>
    /// <param name="provider">
    /// A configured provider.
    /// </param>
    /// <param name="localizer">
    /// A localizer.
    /// </param>
    /// <param name="evaluatorFactory">
    /// An evaluator factory.
    /// </param>
    /// <param name="plugins">
    /// A plugin repository.
    /// </param>
    /// <param name="logger">
    /// A logger.
    /// </param>
    /// <param name="tables">
    /// The tables collection for the data dictionary.
    /// </param>
    /// <param name="security">
    /// The application security object.
    /// </param>
    /// <param name="roles">
    /// The meta data roles collection.
    /// </param>
    /// <param name="config">
    /// A configuration object.
    /// </param>
    /// <param name="app">
    /// The application object.
    /// </param>
    public FieldCollection(IProvider provider, ILocalizer localizer, IEvaluatorFactory<string> evaluatorFactory,
        IPluginRepository plugins, ILogger logger, ITableCollection tables, ISecurity security, IMetaDataRoleCollection roles,
        IConfigurationSettings config, ISQApplication app)
        : base(provider, localizer, evaluatorFactory, plugins, logger)
```

No Func but there is a generic parameter. The resulting topic has no comments for any of the parameters, no summary, and the evaluatorFactory parameter displays as "IEvaluatorFactory`1 evaluatorFactory" in both Syntax and Parameters rather than as a generic.

**Comment by RickStrahl** [comment]
XML comments will fail to generate into the .xml export file if the comments include invalid XML strings. So any quotes, open brackets, etc. Doesn't look like the above has a problem, but I suspect that's what the issue is.

Can you can check the .xml file and see if this function is exported in there?

**Comment by DougHennig** [comment]
Yup, both are there. Here's the XML for the Where method:

```
        <member name="M:Stonefield.Query.DataDictionary.FieldCollection.Where(System.Func{Stonefield.Query.DataDictionary.IField,System.Boolean})">
            <summary>
            Returns a subset of the collection based on a condition.
            </summary>
            <param name="predicate">
            The condition to use.
            </param>
            <returns>
            A set of items satisfying the condition.
            </returns>
        </member>
```

Here it is for the ctor:

```
        <member name="M:Stonefield.Query.DataDictionary.FieldCollection.#ctor(Stonefield.Storage.IProvider,Stonefield.Localization.ILocalizer,Stonefield.ExpressionEvaluator.IEvaluatorFactory{System.String},Stonefield.Query.Plugins.IPluginRepository,Stonefield.Logging.ILogger,Stonefield.Query.DataDictionary.ITableCollection,Stonefield.Security.ISecurity,Stonefield.Query.DataDictionary.IMetaDataRoleCollection,Stonefield.Query.ConfigurationManager.IConfigurationSettings,Stonefield.Query.Application.ISQApplication)">
            <summary>
            Constructor.
            </summary>
            <param name="provider">
            A configured provider.
            </param>
            <param name="localizer">
            A localizer.
            </param>
            <param name="evaluatorFactory">
            An evaluator factory.
            </param>
            <param name="plugins">
            A plugin repository.
            </param>
            <param name="logger">
            A logger.
            </param>
            <param name="tables">
            The tables collection for the data dictionary.
            </param>
            <param name="security">
            The application security object.
            </param>
            <param name="roles">
            The meta data roles collection.
            </param>
            <param name="config">
            A configuration object.
            </param>
            <param name="app">
            The application object.
            </param>
        </member>
```

**Comment by RickStrahl** [comment]
Thanks for reporting this. There were actually a number of related issues that were causing a problem:
- multiple generic parameters
- missing full type name conversion for generic parameters

This should fix quite a few other related issues when importing generic types.

Fixed for next update.

**Comment by DougHennig** [comment]
Most of the methods now import properly, but the ctor still isn't correct: there's no summary (it was just "The constructor" in the class but that doesn't appear in Help Builder), no parameter descriptions, and the generic still appears incorrectly:

public  FieldCollection(IProvider provider,
ILocalizer localizer,
IEvaluatorFactory`1 evaluatorFactory,
IPluginRepository plugins,
ILogger logger,
ITableCollection tables,
ISecurity security,
IMetaDataRoleCollection roles,
IConfigurationSettings config,
ISQApplication app)

evaluatorFactory should be IEvaluatorFactory&lt;string&gt;. It appears in the XML for the class as "Stonefield.ExpressionEvaluator.IEvaluatorFactory{System.String}"

Also, and this is a very minor thing, there's an extra space between "public" and "FieldCollection", likely where the type would go for a normal method.

This is 5.0.135, downloaded this morning.

**Comment by RickStrahl** [comment]
Ok fixed that as well.

Fixed for next release...
